kind: Backend
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: backend1
  namespace: 3scale
spec:
  name: Operated Backend 1
  privateBaseURL: 'https://api.example.com'
  systemName: backend1
providerAccountRef:
    name: tenant-secret