apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crd-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: 3scale
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: ./
    repoURL: https://github.com/adregis/gitops-crd
    targetRevision: main
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true