apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: product1
spec:
  name: "OperatedProduct 1"
  systemName: operatedproduct1
  backendUsages:
    backend1:
      path: /
  applicationPlans:
    plan01:
      name: "My Plan 01"
      setupFee: "00.10"
  policies:
    - configuration:
        http_proxy: http://example.com
        https_proxy: https://example.com
      enabled: true
      name: camel
      version: builtin
    - configuration: {}
      enabled: true
      name: apicast
      version: builtin    
