apiVersion: v1
data:
  adminURL: aHR0cHM6Ly9wcm94eS1hZG1pbi5hcHBzLmNsdXN0ZXItamM3OXcuamM3OXcuc2FuZGJveDE5NS5vcGVudGxjLmNvbQ==
  token: NTc2NTcxMWU0ODdiMTBkNzhlYjdlY2JjMWViNmI1MzYwYTA5NjZiZmQ1ZGUxYTQwMzU3Yjk0MjllZjZjNWYzYg==
kind: Secret
metadata:
  name: threescale-provider-account
  namespace: 3scale
type: Opaque