apiVersion: v1
data:
  adminURL: aHR0cHM6Ly9wcm94eS1hZG1pbi5hcHBzLmNsdXN0ZXItcjQ3cmQucjQ3cmQuc2FuZGJveDE5MDIub3BlbnRsYy5jb20=
  token: ZDQ0Yzg4YjE4YWYxOTFjZWM4MGMxNzIxZTZmZDliMjQ0NjMyM2JmY2I4NDQ5NjgyMTMwYTI3NzU5ZDEyMGZmZQ==
kind: Secret
metadata:
  name: threescale-provider-account
  namespace: 3scale
type: Opaque